

defaults:
  - base_config
  - override network: a21
  - override data: synthetic
  - _self_

data: 
  downsample: 1

mode:
    no_summary_images: True

run:
    distributed: False
    compute_mode: XPU


